query FindAllCategories {
  findAllCategories {
    id
    name
    children {
      name
      id
      children {
        name
        id
        children {
          name
          id
          children {
            name
            id
          }
        }
      }
    }
  }
}
